USE [DbIpLocation]
GO
/****** Object:  Table [dbo].[tblCountries] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblCountries](
	[CountryCode] [varchar](2) NOT NULL,
	[CountryName] [varchar](70) NOT NULL,
 CONSTRAINT [PK_tblCountries] PRIMARY KEY CLUSTERED 
(
	[CountryCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblDataVersion] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblDataVersion](
	[DataVersion] [date] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblIpAddresses] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblIpAddresses](
	[AddressFamily] [tinyint] NOT NULL,
	[StartIpAddressBytes] [varbinary](16) NOT NULL,
	[EndIpAddressBytes] [varbinary](16) NOT NULL,
	[StartIpAddress] [varchar](39) NOT NULL,
	[EndIpAddress] [varchar](39) NOT NULL,
	[Continent] [varchar](5) NULL,
	[Country] [varchar](5) NULL,
	[Region] [varchar](50) NULL,
	[City] [varchar](100) NULL,
	[Latitude] [decimal](10, 5) NULL,
	[Longitude] [decimal](10, 5) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_tblIpAddresses] ******/
CREATE UNIQUE CLUSTERED INDEX [IX_tblIpAddresses] ON [dbo].[tblIpAddresses]
(
	[AddressFamily] ASC,
	[StartIpAddressBytes] ASC,
	[EndIpAddressBytes] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AD', N'Andorra')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AE', N'United Arab Emirates (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AF', N'Afghanistan')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AG', N'Antigua and Barbuda')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AI', N'Anguilla')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AL', N'Albania')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AM', N'Armenia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AO', N'Angola')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AQ', N'Antarctica')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AR', N'Argentina')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AS', N'American Samoa')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AT', N'Austria')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AU', N'Australia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AW', N'Aruba')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AX', N'Åland Islands')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'AZ', N'Azerbaijan')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BA', N'Bosnia and Herzegovina')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BB', N'Barbados')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BD', N'Bangladesh')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BE', N'Belgium')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BF', N'Burkina Faso')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BG', N'Bulgaria')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BH', N'Bahrain')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BI', N'Burundi')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BJ', N'Benin')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BL', N'Saint Barthélemy')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BM', N'Bermuda')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BN', N'Brunei Darussalam')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BO', N'Bolivia (Plurinational State of)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BQ', N'Bonaire, Sint Eustatius and Saba')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BR', N'Brazil')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BS', N'Bahamas (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BT', N'Bhutan')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BV', N'Bouvet Island')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BW', N'Botswana')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BY', N'Belarus')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'BZ', N'Belize')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CA', N'Canada')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CC', N'Cocos (Keeling) Islands (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CD', N'Congo (the Democratic Republic of the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CF', N'Central African Republic (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CG', N'Congo (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CH', N'Switzerland')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CI', N'Côte d''Ivoire')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CK', N'Cook Islands (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CL', N'Chile')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CM', N'Cameroon')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CN', N'China')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CO', N'Colombia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CR', N'Costa Rica')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CU', N'Cuba')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CV', N'Cabo Verde')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CW', N'Curaçao')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CX', N'Christmas Island')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CY', N'Cyprus')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'CZ', N'Czechia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'DE', N'Germany')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'DJ', N'Djibouti')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'DK', N'Denmark')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'DM', N'Dominica')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'DO', N'Dominican Republic (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'DZ', N'Algeria')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'EC', N'Ecuador')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'EE', N'Estonia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'EG', N'Egypt')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'EH', N'Western Sahara')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'ER', N'Eritrea')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'ES', N'Spain')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'ET', N'Ethiopia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'FI', N'Finland')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'FJ', N'Fiji')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'FK', N'Falkland Islands (the) [Malvinas]')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'FM', N'Micronesia (Federated States of)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'FO', N'Faroe Islands (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'FR', N'France')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GA', N'Gabon')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GB', N'United Kingdom of Great Britain and Northern Ireland (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GD', N'Grenada')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GE', N'Georgia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GF', N'French Guiana')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GG', N'Guernsey')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GH', N'Ghana')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GI', N'Gibraltar')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GL', N'Greenland')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GM', N'Gambia (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GN', N'Guinea')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GP', N'Guadeloupe')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GQ', N'Equatorial Guinea')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GR', N'Greece')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GS', N'South Georgia and the South Sandwich Islands')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GT', N'Guatemala')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GU', N'Guam')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GW', N'Guinea-Bissau')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'GY', N'Guyana')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'HK', N'Hong Kong')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'HM', N'Heard Island and McDonald Islands')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'HN', N'Honduras')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'HR', N'Croatia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'HT', N'Haiti')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'HU', N'Hungary')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'ID', N'Indonesia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'IE', N'Ireland')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'IL', N'Israel')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'IM', N'Isle of Man')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'IN', N'India')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'IO', N'British Indian Ocean Territory (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'IQ', N'Iraq')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'IR', N'Iran (Islamic Republic of)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'IS', N'Iceland')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'IT', N'Italy')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'JE', N'Jersey')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'JM', N'Jamaica')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'JO', N'Jordan')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'JP', N'Japan')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'KE', N'Kenya')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'KG', N'Kyrgyzstan')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'KH', N'Cambodia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'KI', N'Kiribati')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'KM', N'Comoros (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'KN', N'Saint Kitts and Nevis')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'KP', N'Korea (the Democratic People''s Republic of)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'KR', N'Korea (the Republic of)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'KW', N'Kuwait')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'KY', N'Cayman Islands (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'KZ', N'Kazakhstan')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'LA', N'Lao People''s Democratic Republic (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'LB', N'Lebanon')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'LC', N'Saint Lucia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'LI', N'Liechtenstein')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'LK', N'Sri Lanka')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'LR', N'Liberia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'LS', N'Lesotho')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'LT', N'Lithuania')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'LU', N'Luxembourg')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'LV', N'Latvia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'LY', N'Libya')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MA', N'Morocco')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MC', N'Monaco')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MD', N'Moldova (the Republic of)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'ME', N'Montenegro')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MF', N'Saint Martin (French part)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MG', N'Madagascar')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MH', N'Marshall Islands (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MK', N'Republic of North Macedonia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'ML', N'Mali')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MM', N'Myanmar')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MN', N'Mongolia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MO', N'Macao')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MP', N'Northern Mariana Islands (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MQ', N'Martinique')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MR', N'Mauritania')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MS', N'Montserrat')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MT', N'Malta')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MU', N'Mauritius')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MV', N'Maldives')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MW', N'Malawi')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MX', N'Mexico')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MY', N'Malaysia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'MZ', N'Mozambique')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'NA', N'Namibia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'NC', N'New Caledonia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'NE', N'Niger (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'NF', N'Norfolk Island')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'NG', N'Nigeria')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'NI', N'Nicaragua')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'NL', N'Netherlands (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'NO', N'Norway')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'NP', N'Nepal')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'NR', N'Nauru')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'NU', N'Niue')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'NZ', N'New Zealand')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'OM', N'Oman')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'PA', N'Panama')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'PE', N'Peru')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'PF', N'French Polynesia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'PG', N'Papua New Guinea')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'PH', N'Philippines (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'PK', N'Pakistan')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'PL', N'Poland')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'PM', N'Saint Pierre and Miquelon')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'PN', N'Pitcairn')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'PR', N'Puerto Rico')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'PS', N'Palestine, State of')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'PT', N'Portugal')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'PW', N'Palau')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'PY', N'Paraguay')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'QA', N'Qatar')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'RE', N'Réunion')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'RO', N'Romania')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'RS', N'Serbia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'RU', N'Russian Federation (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'RW', N'Rwanda')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SA', N'Saudi Arabia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SB', N'Solomon Islands')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SC', N'Seychelles')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SD', N'Sudan (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SE', N'Sweden')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SG', N'Singapore')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SH', N'Saint Helena, Ascension and Tristan da Cunha')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SI', N'Slovenia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SJ', N'Svalbard and Jan Mayen')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SK', N'Slovakia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SL', N'Sierra Leone')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SM', N'San Marino')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SN', N'Senegal')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SO', N'Somalia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SR', N'Suriname')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SS', N'South Sudan')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'ST', N'Sao Tome and Principe')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SV', N'El Salvador')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SX', N'Sint Maarten (Dutch part)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SY', N'Syrian Arab Republic')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'SZ', N'Eswatini')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TC', N'Turks and Caicos Islands (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TD', N'Chad')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TF', N'French Southern Territories (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TG', N'Togo')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TH', N'Thailand')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TJ', N'Tajikistan')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TK', N'Tokelau')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TL', N'Timor-Leste')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TM', N'Turkmenistan')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TN', N'Tunisia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TO', N'Tonga')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TR', N'Turkey')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TT', N'Trinidad and Tobago')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TV', N'Tuvalu')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TW', N'Taiwan (Province of China)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'TZ', N'Tanzania, United Republic of')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'UA', N'Ukraine')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'UG', N'Uganda')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'UM', N'United States Minor Outlying Islands (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'US', N'United States of America (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'UY', N'Uruguay')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'UZ', N'Uzbekistan')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'VA', N'Holy See (the)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'VC', N'Saint Vincent and the Grenadines')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'VE', N'Venezuela (Bolivarian Republic of)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'VG', N'Virgin Islands (British)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'VI', N'Virgin Islands (U.S.)')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'VN', N'Viet Nam')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'VU', N'Vanuatu')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'WF', N'Wallis and Futuna')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'WS', N'Samoa')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'YE', N'Yemen')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'YT', N'Mayotte')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'ZA', N'South Africa')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'ZM', N'Zambia')
INSERT [dbo].[tblCountries] ([CountryCode], [CountryName]) VALUES (N'ZW', N'Zimbabwe')
GO